<div class="card content-card">
    <div class="card-header d-flex align-items-center justify-content-between flex-wrap gap-2">
        <h5 class="mb-0"><i class="fas fa-bullhorn me-2"></i>Announcements Management</h5>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#announcementAddModal">
            <i class="fas fa-plus me-1"></i> Add New
        </button>
    </div>
    <div class="card-body">
        <!-- Search and Filter Section -->
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-text bg-white">
                        <i class="fas fa-search text-muted"></i>
                    </span>
                    <input type="text" 
                           id="announcementSearchInput" 
                           class="form-control" 
                           placeholder="Search by title or description...">
                </div>
            </div>
            <div class="col-md-4">
                <select id="announcementStatusFilter" class="form-select">
                    <option value="">All Status</option>
                    <option value="published">Published</option>
                    <option value="archived">Archived</option>
                </select>
            </div>
            <div class="col-md-2">
                <button id="resetAnnouncementFilters" class="btn btn-outline-secondary w-100">
                    <i class="fas fa-redo me-1"></i> Reset
                </button>
            </div>
        </div>

        <!-- Loading indicator -->
        <div id="announcementLoadingIndicator" class="text-center py-5" style="display: none;">
            <div class="spinner-border text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <p class="mt-2 text-muted">Loading data...</p>
        </div>

        <!-- Table container -->
        <div id="announcementTableContainer">
            <!-- Table will be populated by JavaScript -->
        </div>
    </div>
</div>

<!-- Pagination Section -->
<div class="card-footer bg-white border-top">
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
        <div class="text-muted small">
            <i class="fas fa-info-circle me-1"></i>
            Showing <span id="announcementShowingStart">0</span> to <span id="announcementShowingEnd">0</span> of <span id="announcementTotalRecords">0</span> entries
        </div>
        <nav aria-label="Page navigation">
            <ul class="pagination pagination-sm mb-0" id="announcementPagination">
                <!-- Pagination will be generated by JavaScript -->
            </ul>
        </nav>
        <div class="d-flex align-items-center gap-2">
            <label class="text-muted small mb-0">Rows per page:</label>
            <select id="announcementRowsPerPage" class="form-select form-select-sm" style="width: 75px;">
                <option value="10">10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
        </div>
    </div>
</div>

<!-- Add Modal -->
<div class="modal fade" id="announcementAddModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form id="announcementAddForm" action="{{ route('admin.announcements.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title">Add New Announcement</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Title <span class="text-danger">*</span></label>
                        <input type="text" name="title" class="form-control" required>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Description <span class="text-danger">*</span></label>
                        <textarea name="description" class="form-control" rows="5" required></textarea>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Date <span class="text-danger">*</span></label>
                        <input type="date" name="date" class="form-control" required>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Image</label>
                        <input type="file" name="image" class="form-control" accept="image/*">
                        <div class="form-text">Max size: 5MB. Allowed: JPG, PNG, GIF, WEBP</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="announcementEditModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form id="announcementEditForm" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="modal-header">
                    <h5 class="modal-title">Edit Announcement</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="announcementEditModalBody"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Direct Image Upload Modal -->
<div class="modal fade" id="announcementDirectUploadModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <i class="fas fa-upload me-2"></i>
                    Upload Image to Existing Announcement
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info">
                    <i class="fas fa-info-circle me-2"></i>
                    <strong>Instructions:</strong><br>
                    Select an existing announcement and upload an image for it.<br>
                    The image will be saved to <code>public/images/announcements/{id}.jpg</code>
                </div>
                
                <form id="announcementDirectUploadForm" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label">Select Announcement <span class="text-danger">*</span></label>
                        <select id="announcementSelect" class="form-select" required>
                            <option value="">Loading announcements...</option>
                        </select>
                        <div class="form-text">Choose the announcement you want to add/update the image for</div>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">Select Image <span class="text-danger">*</span></label>
                        <input type="file" id="announcementDirectImage" class="form-control" accept="image/*" required>
                        <div class="form-text">Max size: 5MB. Allowed: JPG, PNG, GIF, WEBP</div>
                    </div>
                    
                    <div id="currentImagePreview" style="display: none;">
                        <label class="form-label">Current Image:</label>
                        <div id="currentImageDisplay"></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" id="announcementDirectUploadBtn" class="btn btn-primary">
                    <i class="fas fa-upload me-1"></i> Upload Image
                </button>
            </div>
        </div>
    </div>
</div>

<style>
    .table-responsive {
        overflow-x: auto;
        min-height: 400px;
    }
    
    #announcementTable {
        min-width: 800px;
        margin-bottom: 0;
    }
    
    #announcementTable tbody tr {
        transition: all 0.2s ease;
    }
    
    #announcementTable tbody tr:hover {
        background-color: #f8f9fa !important;
    }
    
    .status-select {
        font-size: 0.875rem;
        padding: 0.25rem 0.5rem;
        width: 120px;
    }
    
    .btn-sm i {
        font-size: 12px;
    }
    
    .pagination {
        gap: 5px;
        margin: 0;
    }
    
    .pagination .page-item .page-link {
        border-radius: 6px;
        padding: 6px 12px;
        font-size: 13px;
        color: #0E334C;
        border: 1px solid #dee2e6;
        transition: all 0.2s ease;
    }
    
    .pagination .page-item.active .page-link {
        background: #3988BD;
        border-color: #3988BD;
        color: white;
    }
    
    .pagination .page-item .page-link:hover:not(.active) {
        background: #f8f9fa;
        border-color: #3988BD;
        color: #3988BD;
    }
    
    .card-footer {
        background-color: #f8f9fa;
        border-top: 1px solid #dee2e6;
    }
    
    @media (max-width: 768px) {
        .pagination .page-item .page-link {
            padding: 4px 8px;
            font-size: 11px;
        }
        
        .d-flex.justify-content-between {
            flex-direction: column;
            align-items: center !important;
            gap: 10px;
        }
    }

    .modal {
        z-index: 1050;
    }

    .modal-backdrop {
        z-index: 1040;
    }
</style>

<script src="{{ asset('js/admin/announcements.js') }}"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        if (typeof loadAnnouncementData === 'function') {
            loadAnnouncementData();
        }
    });
</script>